import type {
  BooleanLiteral,
  DecoratorContext,
  EmitContext,
  Enum,
  IntrinsicType,
  Model,
  NumericLiteral,
  Scalar,
  StringLiteral,
  Tuple,
  Type,
  Union,
  UnionVariant,
} from "@typespec/compiler";
import {
  emitFile,
  isArrayModelType,
  isRecordModelType,
  navigateProgram,
  resolveEncodedName,
  setTypeSpecNamespace,
} from "@typespec/compiler";
import { getHeaderFieldName, isHeader, isStatusCode } from "@typespec/http";
import { reportDiagnostic, stateKeys, $lib } from "./lib.js";

export { $lib };

export function $tsBrand(context: DecoratorContext, target: Scalar): void {
  context.program.stateMap(stateKeys.tsBrand).set(target, true);
}

setTypeSpecNamespace("Qyl.Api.Schema.Emit.TsTypes", $tsBrand);

const HEADER = "// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n";

function isBuiltin(type: { namespace?: { name?: string; namespace?: { name?: string } } }): boolean {
  let cursor: { name?: string; namespace?: { name?: string } } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace;
  }
  return false;
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const brandBlock: string[] = [];
  const mediaTypeBlock: string[] = [];
  const modelBlock: string[] = [];
  const enumBlock: string[] = [];
  const unionBlock: string[] = [];
  const emittedScalars = new Set<string>();
  const emittedMediaTypes = new Set<string>();
  const emittedModels = new Set<string>();
  const emittedEnums = new Set<string>();
  const emittedUnions = new Set<string>();

  navigateProgram(program, {
    scalar: (s) => {
      if (isBuiltin(s)) return;
      if (!program.stateMap(stateKeys.tsBrand).has(s)) return;
      if (emittedScalars.has(s.name)) return;
      emittedScalars.add(s.name);
      brandBlock.push(`export type ${s.name} = string & { readonly __brand: "${s.name}" };\n`);
    },
    enum: (e) => {
      if (isBuiltin(e)) return;
      if (emittedEnums.has(e.name)) return;
      emittedEnums.add(e.name);
      enumBlock.push(renderEnum(e));
    },
    model: (m) => {
      if (isBuiltin(m)) return;
      if (!m.name) return;
      collectMediaType(program, m, emittedMediaTypes, mediaTypeBlock);
      if (isArrayModelType(m) || isRecordModelType(m)) return;
      if (!hasBodyProperties(program, m)) return;
      const name = emittedModelName(m);
      if (emittedModels.has(name)) return;
      emittedModels.add(name);
      modelBlock.push(renderInterface(program, m, name));
    },
    union: (u) => {
      if (isBuiltin(u) || !u.name || u.name.endsWith("Auth")) return;
      if (emittedUnions.has(u.name)) return;
      emittedUnions.add(u.name);
      unionBlock.push(renderUnion(program, u));
    },
  });

  const out = [HEADER, ...brandBlock, ...mediaTypeBlock, ...enumBlock, ...unionBlock, ...modelBlock];

  const path = `${context.emitterOutputDir}/api.ts`;
  await emitFile(program, { path, content: out.join("\n") });
}

function collectMediaType(
  program: import("@typespec/compiler").Program,
  model: Model,
  emitted: Set<string>,
  output: string[],
): void {
  const name = `${emittedModelName(model)}MediaType`;
  if (emitted.has(name)) return;
  for (const property of model.properties.values()) {
    if (!isHeader(program, property) || getHeaderFieldName(program, property) !== "content-type") continue;
    if (property.type.kind !== "String") continue;
    emitted.add(name);
    output.push(
      `export const ${name} = ${JSON.stringify(property.type.value)} as const;\n` +
      `export type ${name} = typeof ${name};\n`,
    );
  }
}

function renderEnum(e: Enum): string {
  const entries = [...e.members.values()]
    .map((m) => `  ${JSON.stringify(m.name)}: ${JSON.stringify(m.value ?? m.name)}`)
    .join(",\n");
  return `export const ${e.name}Values = {\n${entries},\n} as const;\nexport type ${e.name} = typeof ${e.name}Values[keyof typeof ${e.name}Values];\n`;
}

function renderUnion(program: import("@typespec/compiler").Program, union: Union): string {
  const variants = [...union.variants.values()].map((variant) => mapType(program, variant.type));
  return `export type ${union.name} = ${[...new Set(variants)].join(" | ")};\n`;
}

function renderInterface(
  program: import("@typespec/compiler").Program,
  m: Model,
  emittedName: string,
): string {
  const base = m.baseModel ? ` extends ${emittedModelName(m.baseModel)}` : "";
  const lines: string[] = [`export interface ${emittedName}${base} {`];
  for (const [, prop] of m.properties) {
    if (isHeader(program, prop) || isStatusCode(program, prop)) continue;
    const t = mapType(program, prop.type);
    const q = prop.optional ? "?" : "";
    const wireName = resolveEncodedName(program, prop, "application/json");
    lines.push(`  ${JSON.stringify(wireName)}${q}: ${t};`);
  }
  lines.push("}\n");
  return lines.join("\n");
}

function hasBodyProperties(program: import("@typespec/compiler").Program, model: Model): boolean {
  for (let current: Model | undefined = model; current; current = current.baseModel) {
    for (const property of current.properties.values()) {
      if (!isHeader(program, property) && !isStatusCode(program, property)) return true;
    }
  }
  return false;
}

function emittedModelName(model: Model): string {
  if (!model.templateMapper?.args.length) return model.name;
  const parts = [model.name];
  for (const arg of model.templateMapper.args) {
    if ("kind" in arg && "name" in arg && typeof arg.name === "string") {
      parts.push(pascal(arg.name));
    }
  }
  return parts.join("");
}

function mapType(program: import("@typespec/compiler").Program, type: Type): string {
  switch (type.kind) {
    case "Scalar": {
      const s = type as Scalar;
      if (program.stateMap(stateKeys.tsBrand).has(s)) return s.name;
      if (["int8","int16","int32","int64","uint8","uint16","uint32","uint64","float32","float64","decimal","decimal128"].includes(s.name)) return "number";
      if (s.name === "boolean") return "boolean";
      if (s.name === "bytes") return "string";
      if (s.name === "utcDateTime" || s.name === "offsetDateTime") return "string";
      if (s.name === "plainDate" || s.name === "plainTime") return "string";
      if (s.name === "duration") return "string";
      if (s.name === "url") return "string";
      if (s.name === "string") return "string";
      if (s.baseScalar) return mapType(program, s.baseScalar);
      reportDiagnostic(program, { code: "unmapped-type", target: s, format: { name: `scalar:${s.name}` } });
      return "unknown";
    }
    case "Model":
      if (isArrayModelType(type)) return `${mapType(program, type.indexer!.value)}[]`;
      if (isRecordModelType(type)) return `Record<string, ${mapType(program, type.indexer!.value)}>`;
      return emittedModelName(type);
    case "Enum":
      return (type as Enum).name;
    case "ModelProperty":
      // TypeSpec 1.13 constraint-based member access (e.g. `P.id`): the property
      // reference stands for the referenced property's type.
      return mapType(program, (type as { type: Type }).type);
    case "EnumMember": {
      const m = type as { value?: string | number; name: string };
      const v = m.value ?? m.name;
      return typeof v === "number" ? String(v) : `"${v}"`;
    }
    case "Union":
      if (type.name) return type.name;
      return [...type.variants.values()].map((variant) => mapType(program, variant.type)).join(" | ");
    case "UnionVariant":
      return mapType(program, (type as UnionVariant).type);
    case "Boolean":
      return String((type as BooleanLiteral).value);
    case "String":
      return JSON.stringify((type as StringLiteral).value);
    case "Number":
      return (type as NumericLiteral).valueAsString;
    case "Intrinsic": {
      const name = (type as IntrinsicType).name;
      if (name === "unknown" || name === "null" || name === "never" || name === "void") return name;
      reportDiagnostic(program, { code: "unmapped-type", target: type, format: { name: `intrinsic:${name}` } });
      return "unknown";
    }
    case "Tuple":
      return `[${(type as Tuple).values.map((value) => mapType(program, value)).join(", ")}]`;
    case "StringTemplate":
      return "string";
    default:
      reportDiagnostic(program, { code: "unmapped-type", target: type, format: { name: type.kind } });
      return "unknown";
  }
}

function pascal(value: string): string {
  return value.length === 0 ? value : value[0].toUpperCase() + value.slice(1);
}
