import type {
  BooleanLiteral,
  DecoratorContext,
  EmitContext,
  Enum,
  IntrinsicType,
  Model,
  NumericLiteral,
  Program,
  Scalar,
  StringLiteral,
  Tuple,
  Type,
  Union,
  UnionVariant,
} from "@typespec/compiler";
import {
  emitFile,
  getDiscriminatedUnion,
  getEncode,
  isArrayModelType,
  isRecordModelType,
  navigateProgram,
  resolveEncodedName,
  setTypeSpecNamespace,
} from "@typespec/compiler";
import { getHeaderFieldName, isHeader, isStatusCode } from "@typespec/http";
import { reportDiagnostic, stateKeys, $lib } from "./lib.js";

export { $lib };

export function $tsBrand(context: DecoratorContext, target: Scalar): void {
  context.program.stateMap(stateKeys.tsBrand).set(target, true);
}

setTypeSpecNamespace("Qyl.Api.Schema.Emit.TsTypes", $tsBrand);

const HEADER = "// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n";

function isBuiltin(type: { namespace?: { name?: string; namespace?: { name?: string } } }): boolean {
  let cursor: { name?: string; namespace?: { name?: string } } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace;
  }
  return false;
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const brandBlock: string[] = [];
  const mediaTypeBlock: string[] = [];
  const modelBlock: string[] = [];
  const enumBlock: string[] = [];
  const unionBlock: string[] = [];
  const emittedScalars = new Set<string>();
  const emittedMediaTypes = new Set<string>();
  const emittedModels = new Set<string>();
  const emittedEnums = new Set<string>();
  const emittedUnions = new Set<string>();
  const runtimeUnions: Union[] = [];

  navigateProgram(program, {
    scalar: (s) => {
      if (isBuiltin(s)) return;
      if (!program.stateMap(stateKeys.tsBrand).has(s)) return;
      if (emittedScalars.has(s.name)) return;
      emittedScalars.add(s.name);
      brandBlock.push(`export type ${s.name} = string & { readonly __brand: "${s.name}" };\n`);
    },
    enum: (e) => {
      if (isBuiltin(e)) return;
      if (emittedEnums.has(e.name)) return;
      emittedEnums.add(e.name);
      enumBlock.push(renderEnum(e));
    },
    model: (m) => {
      if (isBuiltin(m)) return;
      if (!m.name) return;
      collectMediaType(program, m, emittedMediaTypes, mediaTypeBlock);
      if (isArrayModelType(m)) return;
      if (isRecordModelType(m)) {
        if (m.name === "Record" || emittedModels.has(m.name)) return;
        emittedModels.add(m.name);
        modelBlock.push(renderRecordInterface(program, m));
        return;
      }
      const isExplicitEmptyModel = m.properties.size === 0 && !m.baseModel;
      if (!hasBodyProperties(program, m) && !isExplicitEmptyModel) return;
      const name = emittedModelName(m);
      if (emittedModels.has(name)) return;
      emittedModels.add(name);
      modelBlock.push(renderInterface(program, m, name));
    },
    union: (u) => {
      if (isBuiltin(u) || !u.name || u.name.endsWith("Auth")) return;
      if (emittedUnions.has(u.name)) return;
      emittedUnions.add(u.name);
      unionBlock.push(renderUnion(program, u));
      if (mixedUnionShape(program, u)) runtimeUnions.push(u);
    },
  });

  const out = [HEADER, ...brandBlock, ...mediaTypeBlock, ...enumBlock, ...unionBlock, ...modelBlock];

  const path = `${context.emitterOutputDir}/api.ts`;
  await emitFile(program, { path, content: out.join("\n") });

  const runtime = [HEADER, ...runtimeUnions.map((u) => renderMixedUnionRuntime(program, u))];
  await emitFile(program, { path: `${context.emitterOutputDir}/runtime.ts`, content: runtime.join("\n") });
}

type MixedUnionShape = {
  hasNull: boolean;
  primitives: Array<"string" | "boolean" | "number">;
  arrayOfSelf: boolean;
  /** The one object-shaped member: a model, or a discriminated union of models. */
  objectMember?: { name: string; type: Model | Union };
};

/**
 * A named union of bare JSON primitives (and optionally an array of itself) plus one
 * object-shaped member, such as AttributeValue. Mirrors the C# emitter's rule so both
 * languages read the same node the same way.
 */
function mixedUnionShape(program: Program, union: Union): MixedUnionShape | undefined {
  if (!union.name) return undefined;
  const shape: MixedUnionShape = { hasNull: false, primitives: [], arrayOfSelf: false };
  for (const [name, variant] of union.variants) {
    const t = variant.type;
    if (t.kind === "Intrinsic" && t.name === "null") { shape.hasNull = true; continue; }
    if (t.kind === "Scalar") {
      const mapped = mapType(program, t);
      if (mapped === "string" || mapped === "boolean" || mapped === "number") { shape.primitives.push(mapped); continue; }
      return undefined;
    }
    if (t.kind === "Model" && isArrayModelType(t)) {
      if (t.indexer?.value === union) { shape.arrayOfSelf = true; continue; }
      return undefined;
    }
    const isObjectMember = (t.kind === "Model" && !isRecordModelType(t)) ||
      (t.kind === "Union" && getDiscriminatedUnion(program, t)[0] !== undefined);
    if (!isObjectMember || shape.objectMember) return undefined;
    shape.objectMember = { name: String(name), type: t as Model | Union };
  }
  const hasPrimitiveSide = shape.primitives.length > 0 || shape.arrayOfSelf;
  return hasPrimitiveSide && shape.objectMember ? shape : undefined;
}

/**
 * The structural half of the decoder: an exhaustive matcher over every variant, with the
 * object member's discriminated variants flattened into it. Presentation policy is written
 * by hand over this, never generated.
 */
function renderMixedUnionRuntime(program: Program, union: Union): string {
  const shape = mixedUnionShape(program, union)!;
  const name = union.name!;
  const member = shape.objectMember!;
  const imports = new Set<string>([name]);
  const handlers: string[] = [];
  const dispatch: string[] = [];
  for (const [variantName, variant] of union.variants) {
    const key = String(variantName);
    const t = variant.type;
    if (t.kind === "Intrinsic") {
      handlers.push(`  ${key}: () => R;`);
      dispatch.push(`  if (value === null) return handlers.${key}();`);
    } else if (t.kind === "Scalar") {
      const mapped = mapType(program, t);
      handlers.push(`  ${key}: (value: ${mapped}) => R;`);
      dispatch.push(`  if (typeof value === "${mapped}") return handlers.${key}(value);`);
    } else if (t.kind === "Model" && isArrayModelType(t)) {
      handlers.push(`  ${key}: (value: ${name}[]) => R;`);
      dispatch.push(`  if (Array.isArray(value)) return handlers.${key}(value);`);
    }
  }
  let tagsBlock = "";
  if (member.type.kind === "Union") {
    const [discriminated] = getDiscriminatedUnion(program, member.type);
    const tag = discriminated!.options.discriminatorPropertyName;
    const memberName = member.type.name!;
    imports.add(memberName);
    const tags: string[] = [];
    const cases: string[] = [];
    for (const [tagValue, variantType] of discriminated!.variants) {
      const typeName = mapType(program, variantType);
      imports.add(typeName);
      tags.push(JSON.stringify(tagValue));
      handlers.push(`  ${tagValue}: (value: ${typeName}) => R;`);
      cases.push(`    case ${JSON.stringify(tagValue)}: return handlers.${tagValue}(value);`);
    }
    tagsBlock =
      `export const ${memberName}Tags = [${tags.join(", ")}] as const;\n` +
      `export type ${memberName}Tag = typeof ${memberName}Tags[number];\n\n` +
      `export function is${memberName}(value: unknown): value is ${memberName} {\n` +
      `  return typeof value === "object" && value !== null && !Array.isArray(value)\n` +
      `    && (${memberName}Tags as readonly string[]).includes(String((value as { ${tag}?: unknown }).${tag}));\n}\n`;
    dispatch.push(
      `  switch (value.${tag}) {\n${cases.join("\n")}\n` +
      `    default:\n      throw new TypeError(\`${memberName} has unknown ${tag} tag '\${String((value as { ${tag}?: unknown }).${tag})}'.\`);\n  }`,
    );
  } else {
    const typeName = mapType(program, member.type);
    imports.add(typeName);
    handlers.push(`  ${member.name}: (value: ${typeName}) => R;`);
    dispatch.push(`  return handlers.${member.name}(value);`);
  }
  return (
    `import type { ${[...imports].sort().join(", ")} } from "./api.js";\n\n` +
    tagsBlock +
    `\nexport interface ${name}Handlers<R> {\n${handlers.join("\n")}\n}\n\n` +
    `/** Exhaustive over every ${name} variant; a handler per variant, no default. */\n` +
    `export function match${name}<R>(value: ${name}, handlers: ${name}Handlers<R>): R {\n${dispatch.join("\n")}\n}\n`
  );
}

function collectMediaType(
  program: Program,
  model: Model,
  emitted: Set<string>,
  output: string[],
): void {
  const name = `${emittedModelName(model)}MediaType`;
  if (emitted.has(name)) return;
  for (const property of model.properties.values()) {
    if (!isHeader(program, property) || getHeaderFieldName(program, property) !== "content-type") continue;
    if (property.type.kind !== "String") continue;
    emitted.add(name);
    output.push(
      `export const ${name} = ${JSON.stringify(property.type.value)} as const;\n` +
      `export type ${name} = typeof ${name};\n`,
    );
  }
}

function renderEnum(e: Enum): string {
  const entries = [...e.members.values()]
    .map((m) => `  ${JSON.stringify(m.name)}: ${JSON.stringify(m.value ?? m.name)}`)
    .join(",\n");
  return `export const ${e.name}Values = {\n${entries},\n} as const;\nexport type ${e.name} = typeof ${e.name}Values[keyof typeof ${e.name}Values];\n`;
}

function renderUnion(program: Program, union: Union): string {
  const variants = [...union.variants.values()].map((variant) => mapType(program, variant.type));
  return `export type ${union.name} = ${[...new Set(variants)].join(" | ")};\n`;
}

function renderInterface(
  program: Program,
  m: Model,
  emittedName: string,
): string {
  const base = m.baseModel ? ` extends ${emittedModelName(m.baseModel)}` : "";
  const lines: string[] = [`export interface ${emittedName}${base} {`];
  for (const [, prop] of m.properties) {
    if (isHeader(program, prop) || isStatusCode(program, prop)) continue;
    const t = mapType(program, prop.type);
    const q = prop.optional ? "?" : "";
    const wireName = resolveEncodedName(program, prop, "application/json");
    lines.push(`  ${JSON.stringify(wireName)}${q}: ${t};`);
  }
  lines.push("}\n");
  return lines.join("\n");
}

function renderRecordInterface(
  program: Program,
  model: Model,
): string {
  const value = model.indexer?.value;
  if (!value) throw new Error(`Named record '${model.name}' has no indexer value.`);
  return `export interface ${model.name} {\n  [key: string]: ${mapType(program, value)};\n}\n`;
}

function hasBodyProperties(program: Program, model: Model): boolean {
  for (let current: Model | undefined = model; current; current = current.baseModel) {
    for (const property of current.properties.values()) {
      if (!isHeader(program, property) && !isStatusCode(program, property)) return true;
    }
  }
  return false;
}

function emittedModelName(model: Model): string {
  if (!model.templateMapper?.args.length) return model.name;
  const parts = [model.name];
  for (const arg of model.templateMapper.args) {
    if ("kind" in arg && "name" in arg && typeof arg.name === "string") {
      parts.push(pascal(arg.name));
    }
  }
  return parts.join("");
}

function mapType(program: Program, type: Type): string {
  switch (type.kind) {
    case "Scalar": {
      const s = type as Scalar;
      if (program.stateMap(stateKeys.tsBrand).has(s)) return s.name;
      if (getEncode(program, s)?.type.name === "string") return "string";
      if (["int8","int16","int32","int64","uint8","uint16","uint32","uint64","float32","float64","decimal","decimal128"].includes(s.name)) return "number";
      if (s.name === "boolean") return "boolean";
      if (s.name === "bytes") return "string";
      if (s.name === "utcDateTime" || s.name === "offsetDateTime") return "string";
      if (s.name === "plainDate" || s.name === "plainTime") return "string";
      if (s.name === "duration") return "string";
      if (s.name === "url") return "string";
      if (s.name === "string") return "string";
      if (s.baseScalar) return mapType(program, s.baseScalar);
      reportDiagnostic(program, { code: "unmapped-type", target: s, format: { name: `scalar:${s.name}` } });
      return "unknown";
    }
    case "Model":
      if (isArrayModelType(type)) return `${mapType(program, type.indexer!.value)}[]`;
      if (isRecordModelType(type)) {
        if (type.name && type.name !== "Record") return emittedModelName(type);
        return `Record<string, ${mapType(program, type.indexer!.value)}>`;
      }
      return emittedModelName(type);
    case "Enum":
      return (type as Enum).name;
    case "ModelProperty":
      // TypeSpec 1.13 constraint-based member access (e.g. `P.id`): the property
      // reference stands for the referenced property's type.
      return mapType(program, (type as { type: Type }).type);
    case "EnumMember": {
      const m = type as { value?: string | number; name: string };
      const v = m.value ?? m.name;
      return typeof v === "number" ? String(v) : `"${v}"`;
    }
    case "Union":
      if (type.name) return type.name;
      return [...type.variants.values()].map((variant) => mapType(program, variant.type)).join(" | ");
    case "UnionVariant":
      return mapType(program, (type as UnionVariant).type);
    case "Boolean":
      return String((type as BooleanLiteral).value);
    case "String":
      return JSON.stringify((type as StringLiteral).value);
    case "Number":
      return (type as NumericLiteral).valueAsString;
    case "Intrinsic": {
      const name = (type as IntrinsicType).name;
      if (name === "unknown" || name === "null" || name === "never" || name === "void") return name;
      reportDiagnostic(program, { code: "unmapped-type", target: type, format: { name: `intrinsic:${name}` } });
      return "unknown";
    }
    case "Tuple":
      return `[${(type as Tuple).values.map((value) => mapType(program, value)).join(", ")}]`;
    case "StringTemplate":
      return "string";
    default:
      reportDiagnostic(program, { code: "unmapped-type", target: type, format: { name: type.kind } });
      return "unknown";
  }
}

function pascal(value: string): string {
  return value.length === 0 ? value : value[0].toUpperCase() + value.slice(1);
}
