import type { EmitContext, Enum, Model, Program, Union } from "@typespec/compiler";
import { emitFile, navigateProgram, resolveEncodedName } from "@typespec/compiler";
import { getHeaderFieldName, isHeader, isStatusCode } from "@typespec/http";
import {
  getCsharpNamespace,
  getCsharpPolymorphicDiscriminator,
  hasCsharpPolymorphic,
  hasCsharpRecord,
} from "./decorators.js";
import { mapType } from "./type-map.js";

const HEADER = "﻿// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n#nullable enable\n\nusing System.Text.Json;\nusing System.Text.Json.Serialization;\n";

type Bucket = {
  namespace: string;
  models: Array<[Model, string]>;
  enums: Enum[];
  unions: Union[];
  mediaTypes: Map<string, string>;
};

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const buckets = new Map<string, Bucket>();
  const emittedNames = new Set<string>();

  navigateProgram(program, {
    model: (m) => {
      if (isInTypeSpec(m)) return;
      if (!m.name) return;
      const ns = resolveNamespace(program, m);
      if (!ns) return;
      collectMediaType(program, m, getBucket(buckets, ns));
      if (!inheritedProperties(m).some((property) => !isHttpMetadata(program, property))) return;
      // Template instantiations share the base name (`CursorPage`); use the instantiated
      // form `CursorPageTrace` so each instantiation produces a distinct type. Template
      // DEFINITIONS are not navigated, so this only fires on concrete instantiations.
      const emittedName = instantiationName(m);
      const key = `${ns}.${emittedName}`;
      if (emittedNames.has(key)) return;
      emittedNames.add(key);
      getBucket(buckets, ns).models.push([m, emittedName]);
    },
    enum: (e) => {
      if (isInTypeSpec(e)) return;
      const ns = resolveNamespace(program, e);
      if (!ns) return;
      getBucket(buckets, ns).enums.push(e);
    },
    union: (u) => {
      if (isInTypeSpec(u) || !u.name || !hasCsharpPolymorphic(program, u)) return;
      const ns = resolveNamespace(program, u);
      if (!ns) return;
      getBucket(buckets, ns).unions.push(u);
    },
  });

  for (const [ns, bucket] of buckets) {
    const path = `${context.emitterOutputDir}/${ns.replace(/\./g, "/")}.cs`;
    await emitFile(program, { path, content: renderBucket(program, bucket) });
  }
}

function instantiationName(model: Model): string {
  if (!model.templateMapper?.args.length) return model.name;
  const parts = [model.name];
  for (const arg of model.templateMapper.args) {
    if ("kind" in arg && "name" in arg && typeof arg.name === "string") {
      parts.push(pascal(arg.name));
    }
  }
  return parts.join("");
}

function isInTypeSpec(type: { namespace?: { name?: string; namespace?: unknown } }): boolean {
  let cursor: { name?: string; namespace?: unknown } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace as typeof cursor;
  }
  return false;
}

function getBucket(buckets: Map<string, Bucket>, namespace: string): Bucket {
  let b = buckets.get(namespace);
  if (!b) {
    b = { namespace, models: [], enums: [], unions: [], mediaTypes: new Map() };
    buckets.set(namespace, b);
  }
  return b;
}

function resolveNamespace(program: Program, type: Model | Enum | Union): string | undefined {
  const own = getCsharpNamespace(program, type);
  if (own) return own;
  let cursor = type.namespace;
  while (cursor) {
    const mapped = getCsharpNamespace(program, cursor);
    if (mapped) return mapped;
    cursor = cursor.namespace;
  }
  return undefined;
}

function renderBucket(program: Program, bucket: Bucket): string {
  const out: string[] = [HEADER];
  out.push(`namespace ${bucket.namespace};\n`);
  for (const [name, value] of bucket.mediaTypes) out.push(renderMediaType(name, value));
  for (const union of bucket.unions) out.push(renderPolymorphicUnion(program, union));
  const internalBases = polymorphicBaseModels(bucket.unions);
  for (const [m, name] of bucket.models) {
    if (!internalBases.has(m)) out.push(renderModel(program, m, name, bucket.unions));
  }
  for (const e of bucket.enums) out.push(renderEnum(program, e));
  return out.join("\n");
}

function polymorphicBaseModels(unions: Union[]): Set<Model> {
  const result = new Set<Model>();
  for (const union of unions) {
    for (const variant of union.variants.values()) {
      if (variant.type.kind === "Model" && variant.type.baseModel) result.add(variant.type.baseModel);
    }
  }
  return result;
}

function collectMediaType(program: Program, model: Model, bucket: Bucket): void {
  for (const property of model.properties.values()) {
    if (!isHeader(program, property) || getHeaderFieldName(program, property) !== "content-type") continue;
    if (property.type.kind !== "String") continue;
    bucket.mediaTypes.set(`${model.name}MediaType`, property.type.value);
  }
}

function renderMediaType(name: string, value: string): string {
  return `public static class ${name}\n{\n    public const string Value = "${escapeCsharpString(value)}";\n}\n`;
}

function renderModel(program: Program, model: Model, emittedName: string, unions: Union[]): string {
  const asRecord = hasCsharpRecord(program, model);
  const keyword = asRecord ? "public sealed record" : "public sealed class";
  const union = unions.find((candidate) =>
    [...candidate.variants.values()].some((variant) => variant.type === model),
  );
  const implementsUnion = union ? ` : ${union.name}` : "";
  const discriminator = union ? getCsharpPolymorphicDiscriminator(program, union) : undefined;
  const props: string[] = [];
  for (const prop of inheritedProperties(model)) {
    if (isHttpMetadata(program, prop)) continue;
    const jsonName = escapeCsharpString(resolveEncodedName(program, prop, "application/json"));
    if (discriminator && jsonName === discriminator) continue;
    const type = mapType(program, prop.type);
    const name = pascal(prop.name);
    if (prop.optional) {
      props.push(`    [JsonPropertyName("${jsonName}")]\n    public ${type}? ${name} { get; init; }`);
    } else {
      props.push(`    [JsonPropertyName("${jsonName}")]\n    public required ${type} ${name} { get; init; }`);
    }
  }
  const body = props.length ? `\n${props.join("\n")}\n` : "\n";
  return `${keyword} ${emittedName}${implementsUnion}\n{${body}}\n`;
}

function renderPolymorphicUnion(program: Program, union: Union): string {
  const variants = [...union.variants.values()].map((variant) => {
    if (variant.type.kind !== "Model") {
      throw new Error(`@csharpPolymorphic union '${union.name}' contains non-model variant '${String(variant.name)}'.`);
    }
    return variant.type;
  });
  const discriminator = getCsharpPolymorphicDiscriminator(program, union);
  if (discriminator) {
    const attributes = variants.map((model) => {
      const property = inheritedProperties(model).find((candidate) =>
        resolveEncodedName(program, candidate, "application/json") === discriminator,
      );
      if (!property || property.type.kind !== "String") {
        throw new Error(
          `@csharpPolymorphic union '${union.name}' variant '${model.name}' must have literal string '${discriminator}'.`,
        );
      }
      return `[JsonDerivedType(typeof(${model.name}), "${escapeCsharpString(property.type.value)}")]`;
    });
    return `[JsonPolymorphic(TypeDiscriminatorPropertyName = "${escapeCsharpString(discriminator)}")]\n${attributes.join("\n")}\npublic interface ${union.name}\n{\n}\n`;
  }

  const selectors = variants.map((model) => {
    const property = [...model.properties.values()].find((candidate) =>
      !candidate.optional && !isHttpMetadata(program, candidate),
    );
    if (!property) {
      throw new Error(
        `@csharpPolymorphic union '${union.name}' variant '${model.name}' needs a required distinguishing property.`,
      );
    }
    return {
      model,
      wireName: resolveEncodedName(program, property, "application/json"),
    };
  });
  const converter = `${union.name}JsonConverter`;
  const presence = selectors.map(({ model, wireName }) =>
    `        var has${model.name} = root.TryGetProperty("${escapeCsharpString(wireName)}", out _);`,
  ).join("\n");
  const count = selectors.map(({ model }) => `(has${model.name} ? 1 : 0)`).join(" + ");
  // GetTypeInfo-based overloads keep the converter trim/AOT-warning-free (IL2026/IL3050): the
  // reflection-annotated Serialize<T>/Deserialize<T>(options) overloads warn statically even when
  // the options carry a source-gen resolver at runtime.
  const reads = selectors.map(({ model }) =>
    `        if (has${model.name}) return (${model.name}?)root.Deserialize(options.GetTypeInfo(typeof(${model.name})));`,
  ).join("\n");
  const writes = selectors.map(({ model }) =>
    `            case ${model.name} typed:\n                JsonSerializer.Serialize(writer, typed, options.GetTypeInfo(typeof(${model.name})));\n                return;`,
  ).join("\n");
  return `[JsonConverter(typeof(${converter}))]\npublic interface ${union.name}\n{\n}\n\npublic sealed class ${converter} : JsonConverter<${union.name}>\n{\n    public override ${union.name}? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)\n    {\n        if (reader.TokenType == JsonTokenType.Null) return null;\n        using var document = JsonDocument.ParseValue(ref reader);\n        var root = document.RootElement;\n        if (root.ValueKind != JsonValueKind.Object) throw new JsonException("${union.name} must be a JSON object.");\n${presence}\n        if (${count} != 1) throw new JsonException("${union.name} must contain exactly one variant field.");\n${reads}\n        throw new JsonException("${union.name} did not match a known variant.");\n    }\n\n    public override void Write(Utf8JsonWriter writer, ${union.name} value, JsonSerializerOptions options)\n    {\n        switch (value)\n        {\n${writes}\n            default:\n                throw new JsonException($"Unknown ${union.name} implementation '{value.GetType().FullName}'.");\n        }\n    }\n}\n`;
}

function isHttpMetadata(program: Program, property: import("@typespec/compiler").ModelProperty): boolean {
  return isHeader(program, property) || isStatusCode(program, property);
}

function inheritedProperties(model: Model): import("@typespec/compiler").ModelProperty[] {
  const byName = new Map<string, import("@typespec/compiler").ModelProperty>();
  const lineage: Model[] = [];
  for (let current: Model | undefined = model; current; current = current.baseModel) {
    lineage.unshift(current);
  }
  for (const current of lineage) {
    for (const property of current.properties.values()) byName.set(property.name, property);
  }
  return [...byName.values()];
}

function renderEnum(_program: Program, enm: Enum): string {
  const enumMembers = [...enm.members.values()];
  const usesStringValues = enumMembers.some((m) => typeof m.value !== "number");
  const converter = usesStringValues
    ? `[JsonConverter(typeof(JsonStringEnumConverter<${enm.name}>))]\n`
    : "";
  const members = enumMembers.map((m) => {
    const wireValue = typeof m.value === "string" ? m.value : m.name;
    const nameAttribute = usesStringValues
      ? `    [JsonStringEnumMemberName("${escapeCsharpString(wireValue)}")]\n`
      : "";
    const valueSuffix = typeof m.value === "number" ? ` = ${m.value}` : "";
    return `${nameAttribute}    ${pascal(m.name)}${valueSuffix}`;
  }).join(",\n");
  return `${converter}public enum ${enm.name}\n{\n${members}\n}\n`;
}

function pascal(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

function escapeCsharpString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
