import type { EmitContext, Enum, Model, Program } from "@typespec/compiler";
import { emitFile, navigateProgram, resolveEncodedName } from "@typespec/compiler";
import { isHeader, isStatusCode } from "@typespec/http";
import { getCsharpNamespace, hasCsharpRecord } from "./decorators.js";
import { mapType } from "./type-map.js";

const HEADER = "﻿// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n#nullable enable\n\nusing System.Text.Json.Serialization;\n";

type Bucket = { namespace: string; models: Array<[Model, string]>; enums: Enum[] };

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const buckets = new Map<string, Bucket>();
  const emittedNames = new Set<string>();

  navigateProgram(program, {
    model: (m) => {
      if (isInTypeSpec(m)) return;
      if (!m.name) return;
      if (!inheritedProperties(m).some((property) => !isHttpMetadata(program, property))) return;
      const ns = resolveNamespace(program, m);
      if (!ns) return;
      // Template instantiations share the base name (`CursorPage`); use the instantiated
      // form `CursorPageTrace` so each instantiation produces a distinct type. Template
      // DEFINITIONS are not navigated, so this only fires on concrete instantiations.
      const emittedName = instantiationName(m);
      const key = `${ns}.${emittedName}`;
      if (emittedNames.has(key)) return;
      emittedNames.add(key);
      getBucket(buckets, ns).models.push([m, emittedName]);
    },
    enum: (e) => {
      if (isInTypeSpec(e)) return;
      const ns = resolveNamespace(program, e);
      if (!ns) return;
      getBucket(buckets, ns).enums.push(e);
    },
  });

  for (const [ns, bucket] of buckets) {
    const path = `${context.emitterOutputDir}/${ns.replace(/\./g, "/")}.cs`;
    await emitFile(program, { path, content: renderBucket(program, bucket) });
  }
}

function instantiationName(model: Model): string {
  if (!model.templateMapper?.args.length) return model.name;
  const parts = [model.name];
  for (const arg of model.templateMapper.args) {
    if ("kind" in arg && "name" in arg && typeof arg.name === "string") {
      parts.push(pascal(arg.name));
    }
  }
  return parts.join("");
}

function isInTypeSpec(type: { namespace?: { name?: string; namespace?: unknown } }): boolean {
  let cursor: { name?: string; namespace?: unknown } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace as typeof cursor;
  }
  return false;
}

function getBucket(buckets: Map<string, Bucket>, namespace: string): Bucket {
  let b = buckets.get(namespace);
  if (!b) {
    b = { namespace, models: [], enums: [] };
    buckets.set(namespace, b);
  }
  return b;
}

function resolveNamespace(program: Program, type: Model | Enum): string | undefined {
  const own = getCsharpNamespace(program, type);
  if (own) return own;
  let cursor = type.namespace;
  while (cursor) {
    const mapped = getCsharpNamespace(program, cursor);
    if (mapped) return mapped;
    cursor = cursor.namespace;
  }
  return undefined;
}

function renderBucket(program: Program, bucket: Bucket): string {
  const out: string[] = [HEADER];
  out.push(`namespace ${bucket.namespace};\n`);
  for (const [m, name] of bucket.models) out.push(renderModel(program, m, name));
  for (const e of bucket.enums) out.push(renderEnum(program, e));
  return out.join("\n");
}

function renderModel(program: Program, model: Model, emittedName: string): string {
  const asRecord = hasCsharpRecord(program, model);
  const keyword = asRecord ? "public sealed record" : "public sealed class";
  const props: string[] = [];
  for (const prop of inheritedProperties(model)) {
    if (isHttpMetadata(program, prop)) continue;
    const type = mapType(program, prop.type);
    const name = pascal(prop.name);
    const jsonName = escapeCsharpString(resolveEncodedName(program, prop, "application/json"));
    if (prop.optional) {
      props.push(`    [JsonPropertyName("${jsonName}")]\n    public ${type}? ${name} { get; init; }`);
    } else {
      props.push(`    [JsonPropertyName("${jsonName}")]\n    public required ${type} ${name} { get; init; }`);
    }
  }
  const body = props.length ? `\n${props.join("\n")}\n` : "\n";
  return `${keyword} ${emittedName}\n{${body}}\n`;
}

function isHttpMetadata(program: Program, property: import("@typespec/compiler").ModelProperty): boolean {
  return isHeader(program, property) || isStatusCode(program, property);
}

function inheritedProperties(model: Model): import("@typespec/compiler").ModelProperty[] {
  const byName = new Map<string, import("@typespec/compiler").ModelProperty>();
  const lineage: Model[] = [];
  for (let current: Model | undefined = model; current; current = current.baseModel) {
    lineage.unshift(current);
  }
  for (const current of lineage) {
    for (const property of current.properties.values()) byName.set(property.name, property);
  }
  return [...byName.values()];
}

function renderEnum(_program: Program, enm: Enum): string {
  const enumMembers = [...enm.members.values()];
  const usesStringValues = enumMembers.some((m) => typeof m.value !== "number");
  const converter = usesStringValues
    ? `[JsonConverter(typeof(JsonStringEnumConverter<${enm.name}>))]\n`
    : "";
  const members = enumMembers.map((m) => {
    const wireValue = typeof m.value === "string" ? m.value : m.name;
    const nameAttribute = usesStringValues
      ? `    [JsonStringEnumMemberName("${escapeCsharpString(wireValue)}")]\n`
      : "";
    const valueSuffix = typeof m.value === "number" ? ` = ${m.value}` : "";
    return `${nameAttribute}    ${pascal(m.name)}${valueSuffix}`;
  }).join(",\n");
  return `${converter}public enum ${enm.name}\n{\n${members}\n}\n`;
}

function pascal(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

function escapeCsharpString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
