import type { EmitContext, Enum, Model, ModelProperty, Program, Scalar, Type, Union } from "@typespec/compiler";
import { emitFile, getDiscriminatedUnion, getEncode, isArrayModelType, navigateProgram, resolveEncodedName } from "@typespec/compiler";
import { getHeaderFieldName, isHeader, isStatusCode } from "@typespec/http";
import {
  getCsharpNamespace,
  getCsharpPolymorphicDiscriminator,
  hasCsharpBrand,
  hasCsharpPolymorphic,
} from "./decorators.js";
import { isDiscriminatedUnion, isNamedFloatingPointUnion, mapType, mixedUnionShape } from "./type-map.js";
import type { MixedUnionShape } from "./type-map.js";

const HEADER = "﻿// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n#nullable enable\n\nusing System.Text.Json;\nusing System.Text.Json.Serialization;\n";

type Bucket = {
  namespace: string;
  scalars: Scalar[];
  models: Array<[Model, string]>;
  enums: Enum[];
  unions: Union[];
  mediaTypes: Map<string, string>;
};

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const buckets = new Map<string, Bucket>();
  const emittedNames = new Set<string>();

  navigateProgram(program, {
    model: (m) => {
      if (isInTypeSpec(m)) return;
      if (!m.name) return;
      const ns = resolveNamespace(program, m);
      if (!ns) return;
      collectMediaType(program, m, getBucket(buckets, ns));
      const hasBodyProperty = inheritedProperties(m)
        .some((property) => !isHttpMetadata(program, property));
      const isExplicitEmptyModel = m.properties.size === 0 && !m.baseModel;
      if (!hasBodyProperty && !isExplicitEmptyModel) return;
      // Template instantiations share the base name (`CursorPage`); use the instantiated
      // form `CursorPageTrace` so each instantiation produces a distinct type. Template
      // DEFINITIONS are not navigated, so this only fires on concrete instantiations.
      const emittedName = instantiationName(m);
      const key = `${ns}.${emittedName}`;
      if (emittedNames.has(key)) return;
      emittedNames.add(key);
      getBucket(buckets, ns).models.push([m, emittedName]);
    },
    enum: (e) => {
      if (isInTypeSpec(e)) return;
      const ns = resolveNamespace(program, e);
      if (!ns) return;
      getBucket(buckets, ns).enums.push(e);
    },
    union: (u) => {
      if (isInTypeSpec(u) || !u.name) return;
      if (!hasCsharpPolymorphic(program, u) && !isDiscriminatedUnion(program, u) && !mixedUnionShape(program, u)) return;
      const ns = resolveNamespace(program, u);
      if (!ns) return;
      getBucket(buckets, ns).unions.push(u);
    },
    scalar: (s) => {
      if (isInTypeSpec(s) || !s.name || !hasCsharpBrand(program, s)) return;
      const ns = resolveNamespace(program, s);
      if (!ns) return;
      getBucket(buckets, ns).scalars.push(s);
    },
  });

  for (const [ns, bucket] of buckets) {
    const path = `${context.emitterOutputDir}/${ns.replace(/\./g, "/")}.cs`;
    await emitFile(program, { path, content: renderBucket(program, bucket) });
  }
}

function instantiationName(model: Model): string {
  if (!model.templateMapper?.args.length) return model.name;
  const parts = [model.name];
  for (const arg of model.templateMapper.args) {
    if ("kind" in arg && "name" in arg && typeof arg.name === "string") {
      parts.push(pascal(arg.name));
    }
  }
  return parts.join("");
}

function isInTypeSpec(type: { namespace?: { name?: string; namespace?: unknown } }): boolean {
  let cursor: { name?: string; namespace?: unknown } | undefined = type.namespace;
  while (cursor) {
    if (cursor.name === "TypeSpec") return true;
    cursor = cursor.namespace as typeof cursor;
  }
  return false;
}

function getBucket(buckets: Map<string, Bucket>, namespace: string): Bucket {
  let b = buckets.get(namespace);
  if (!b) {
    b = { namespace, scalars: [], models: [], enums: [], unions: [], mediaTypes: new Map() };
    buckets.set(namespace, b);
  }
  return b;
}

function resolveNamespace(program: Program, type: Model | Enum | Scalar | Union): string | undefined {
  const own = getCsharpNamespace(program, type);
  if (own) return own;
  let cursor = type.namespace;
  while (cursor) {
    const mapped = getCsharpNamespace(program, cursor);
    if (mapped) return mapped;
    cursor = cursor.namespace;
  }
  return undefined;
}

function renderBucket(program: Program, bucket: Bucket): string {
  const out: string[] = [HEADER];
  out.push(`namespace ${bucket.namespace};\n`);
  for (const scalar of bucket.scalars) out.push(renderBrandedScalar(scalar));
  for (const [name, value] of bucket.mediaTypes) out.push(renderMediaType(name, value));
  for (const union of bucket.unions) {
    const mixed = mixedUnionShape(program, union);
    out.push(mixed ? renderMixedUnion(program, union, mixed) : renderPolymorphicUnion(program, union));
  }
  const internalBases = polymorphicBaseModels(bucket.unions);
  for (const [m, name] of bucket.models) {
    if (!internalBases.has(m)) out.push(renderModel(program, m, name, bucket.unions));
  }
  for (const e of bucket.enums) out.push(renderEnum(program, e));
  return out.join("\n");
}

function renderBrandedScalar(scalar: Scalar): string {
  if (!isStringScalar(scalar)) {
    throw new Error(`@csharpBrand scalar '${scalar.name}' must extend string.`);
  }
  const name = scalar.name;
  const converter = `${name}JsonConverter`;
  return `[JsonConverter(typeof(${converter}))]\npublic readonly record struct ${name}(string Value)\n{\n    public override string ToString() => Value;\n}\n\npublic sealed class ${converter} : JsonConverter<${name}>\n{\n    public override ${name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)\n    {\n        if (reader.TokenType != JsonTokenType.String) throw new JsonException("${name} must be a JSON string.");\n        return new ${name}(reader.GetString() ?? throw new JsonException("${name} cannot be null."));\n    }\n\n    public override void Write(Utf8JsonWriter writer, ${name} value, JsonSerializerOptions options) =>\n        writer.WriteStringValue(value.Value);\n}\n`;
}

function isStringScalar(scalar: Scalar): boolean {
  if (scalar.name === "string") return true;
  return scalar.baseScalar ? isStringScalar(scalar.baseScalar) : false;
}

function polymorphicBaseModels(unions: Union[]): Set<Model> {
  const result = new Set<Model>();
  for (const union of unions) {
    for (const variant of union.variants.values()) {
      if (variant.type.kind === "Model" && variant.type.baseModel) result.add(variant.type.baseModel);
    }
  }
  return result;
}

function collectMediaType(program: Program, model: Model, bucket: Bucket): void {
  for (const property of model.properties.values()) {
    if (!isHeader(program, property) || getHeaderFieldName(program, property) !== "content-type") continue;
    if (property.type.kind !== "String") continue;
    bucket.mediaTypes.set(`${model.name}MediaType`, property.type.value);
  }
}

function renderMediaType(name: string, value: string): string {
  return `public static class ${name}\n{\n    public const string Value = "${escapeCsharpString(value)}";\n}\n`;
}

/** The wire discriminator of a tagged union and the tag each variant model carries. */
function taggedUnionInfo(program: Program, union: Union): { property: string; tagOf: (model: Model) => string } | undefined {
  const [discriminated] = getDiscriminatedUnion(program, union);
  if (discriminated) {
    if (discriminated.options.envelope !== "none") {
      throw new Error(`@discriminated union '${union.name}' must use envelope "none"; the emitter has no envelope form.`);
    }
    const tags = new Map<Type, string>();
    for (const [name, type] of discriminated.variants) tags.set(type, name);
    return {
      property: discriminated.options.discriminatorPropertyName,
      tagOf: (model) => {
        const tag = tags.get(model);
        if (tag === undefined) throw new Error(`Model '${model.name}' is not a variant of '${union.name}'.`);
        return tag;
      },
    };
  }
  const property = getCsharpPolymorphicDiscriminator(program, union);
  if (!property) return undefined;
  return {
    property,
    tagOf: (model) => {
      const literal = inheritedProperties(model).find((candidate) =>
        resolveEncodedName(program, candidate, "application/json") === property,
      );
      if (!literal || literal.type.kind !== "String") {
        throw new Error(
          `@csharpPolymorphic union '${union.name}' variant '${model.name}' must have literal string '${property}'.`,
        );
      }
      return literal.type.value;
    },
  };
}

function renderModel(program: Program, model: Model, emittedName: string, unions: Union[]): string {
  const keyword = "public sealed class";
  const union = unions.find((candidate) =>
    !mixedUnionShape(program, candidate) &&
    [...candidate.variants.values()].some((variant) => variant.type === model),
  );
  const implementsUnion = union ? ` : ${union.name}` : "";
  const discriminator = union ? taggedUnionInfo(program, union)?.property : undefined;
  const props: string[] = [];
  for (const prop of inheritedProperties(model)) {
    if (isHttpMetadata(program, prop)) continue;
    const jsonName = escapeCsharpString(resolveEncodedName(program, prop, "application/json"));
    if (discriminator && jsonName === discriminator) continue;
    const type = mapType(program, prop.type);
    const name = pascal(prop.name);
    const numberHandling = renderNumberHandling(program, prop);
    if (prop.optional) {
      const optionalType = type.endsWith("?") ? type : `${type}?`;
      const ignoreNull = "    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n";
      props.push(`${numberHandling}${ignoreNull}    [JsonPropertyName("${jsonName}")]\n    public ${optionalType} ${name} { get; init; }`);
    } else {
      // A required property whose type admits null must be written even when null; a consumer's
      // context-wide WhenWritingNull policy would otherwise drop it and fail its own reader.
      const alwaysWrite = type.endsWith("?") ? "    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]\n" : "";
      props.push(`${numberHandling}${alwaysWrite}    [JsonPropertyName("${jsonName}")]\n    public required ${type} ${name} { get; init; }`);
    }
  }
  const body = props.length ? `\n${props.join("\n")}\n` : "\n";
  return `${keyword} ${emittedName}${implementsUnion}\n{${body}}\n`;
}

function renderNumberHandling(program: Program, property: ModelProperty): string {
  if (isStringEncodedNumber(program, property)) {
    return "    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.WriteAsString)]\n";
  }
  if (isNamedFloatingPointUnion(property.type)) {
    return "    [JsonNumberHandling(JsonNumberHandling.AllowNamedFloatingPointLiterals)]\n";
  }
  return "";
}

function isStringEncodedNumber(program: Program, property: ModelProperty): boolean {
  const direct = getEncode(program, property);
  if (direct?.type.name === "string") return isNumericType(property.type);
  return hasStringEncodedNumericScalar(program, property.type);
}

function hasStringEncodedNumericScalar(program: Program, type: Type): boolean {
  if (type.kind === "Scalar") {
    const scalar = type as Scalar;
    if (getEncode(program, scalar)?.type.name === "string") return isNumericScalar(scalar);
    return scalar.baseScalar ? hasStringEncodedNumericScalar(program, scalar.baseScalar) : false;
  }
  if (type.kind === "Model" && isArrayModelType(type)) {
    return hasStringEncodedNumericScalar(program, type.indexer!.value);
  }
  return false;
}

function isNumericType(type: Type): boolean {
  if (type.kind === "Scalar") return isNumericScalar(type as Scalar);
  return type.kind === "Model" && isArrayModelType(type) && isNumericType(type.indexer!.value);
}

function isNumericScalar(scalar: Scalar): boolean {
  if (["int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "decimal", "decimal128"].includes(scalar.name)) {
    return true;
  }
  return scalar.baseScalar ? isNumericScalar(scalar.baseScalar) : false;
}

function renderPolymorphicUnion(program: Program, union: Union): string {
  const variants = [...union.variants.values()].map((variant) => {
    if (variant.type.kind !== "Model") {
      throw new Error(`@csharpPolymorphic union '${union.name}' contains non-model variant '${String(variant.name)}'.`);
    }
    return variant.type;
  });
  const tagged = taggedUnionInfo(program, union);
  if (tagged) {
    const attributes = variants.map((model) =>
      `[JsonDerivedType(typeof(${model.name}), "${escapeCsharpString(tagged.tagOf(model))}")]`,
    );
    // The tag is a plain property on the wire. System.Text.Json reads it first by default; a
    // consumer that receives it in any position sets AllowOutOfOrderMetadataProperties on its
    // serializer options (or JsonSourceGenerationOptions).
    return `[JsonPolymorphic(TypeDiscriminatorPropertyName = "${escapeCsharpString(tagged.property)}")]\n${attributes.join("\n")}\npublic interface ${union.name}\n{\n}\n`;
  }

  const selectors = variants.map((model) => {
    const property = [...model.properties.values()].find((candidate) =>
      !candidate.optional && !isHttpMetadata(program, candidate),
    );
    if (!property) {
      throw new Error(
        `@csharpPolymorphic union '${union.name}' variant '${model.name}' needs a required distinguishing property.`,
      );
    }
    return {
      model,
      wireName: resolveEncodedName(program, property, "application/json"),
    };
  });
  const converter = `${union.name}JsonConverter`;
  const presence = selectors.map(({ model, wireName }) =>
    `        var has${model.name} = root.TryGetProperty("${escapeCsharpString(wireName)}", out _);`,
  ).join("\n");
  const count = selectors.map(({ model }) => `(has${model.name} ? 1 : 0)`).join(" + ");
  // GetTypeInfo-based overloads keep the converter trim/AOT-warning-free (IL2026/IL3050): the
  // reflection-annotated Serialize<T>/Deserialize<T>(options) overloads warn statically even when
  // the options carry a source-gen resolver at runtime.
  const reads = selectors.map(({ model }) =>
    `        if (has${model.name}) return (${model.name}?)root.Deserialize(options.GetTypeInfo(typeof(${model.name})));`,
  ).join("\n");
  const writes = selectors.map(({ model }) =>
    `            case ${model.name} typed:\n                JsonSerializer.Serialize(writer, typed, options.GetTypeInfo(typeof(${model.name})));\n                return;`,
  ).join("\n");
  return `[JsonConverter(typeof(${converter}))]\npublic interface ${union.name}\n{\n}\n\npublic sealed class ${converter} : JsonConverter<${union.name}>\n{\n    public override ${union.name}? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)\n    {\n        if (reader.TokenType == JsonTokenType.Null) return null;\n        using var document = JsonDocument.ParseValue(ref reader);\n        var root = document.RootElement;\n        if (root.ValueKind != JsonValueKind.Object) throw new JsonException("${union.name} must be a JSON object.");\n${presence}\n        if (${count} != 1) throw new JsonException("${union.name} must contain exactly one variant field.");\n${reads}\n        throw new JsonException("${union.name} did not match a known variant.");\n    }\n\n    public override void Write(Utf8JsonWriter writer, ${union.name} value, JsonSerializerOptions options)\n    {\n        switch (value)\n        {\n${writes}\n            default:\n                throw new JsonException($"Unknown ${union.name} implementation '{value.GetType().FullName}'.");\n        }\n    }\n}\n`;
}

/**
 * A union of bare JSON primitives plus one tagged object member becomes an abstract class with
 * one sealed case per primitive kind and one wrapping the object member, plus a converter that
 * dispatches on the JSON token kind. The object member keeps its own discriminator converter.
 */
function renderMixedUnion(program: Program, union: Union, shape: MixedUnionShape): string {
  const name = union.name!;
  const converter = `${name}JsonConverter`;
  const objectType = mapType(program, shape.objectMember!.type);
  const caseName = (variantName: string) => pascal(variantName);
  const variantNames = new Map<string, string>();
  for (const [variantName, variant] of union.variants) {
    const t = variant.type;
    const key = t.kind === "Intrinsic" ? "null"
      : t.kind === "Scalar" ? mapType(program, t)
      : t.kind === "Model" && isArrayModelType(t) ? "array"
      : "object";
    variantNames.set(key, caseName(String(variantName)));
  }
  const stringCase = shape.primitives.includes("string") ? variantNames.get("string") : undefined;
  const boolCase = shape.primitives.includes("boolean") ? variantNames.get("bool") : undefined;
  const numberCase = shape.primitives.includes("number") ? [...variantNames.entries()].find(([k]) => k !== "string" && k !== "bool" && k !== "null" && k !== "array" && k !== "object")?.[1] : undefined;
  const arrayCase = shape.arrayOfSelf ? variantNames.get("array") : undefined;
  const objectCase = variantNames.get("object")!;
  const elementType = `${name}${shape.hasNull ? "?" : ""}`;

  const cases: string[] = [];
  const reads: string[] = [];
  const writes: string[] = [];
  if (stringCase) {
    cases.push(`    public sealed class ${stringCase}(string value) : ${name}\n    {\n        public string Value { get; } = value;\n    }`);
    reads.push(`            case JsonTokenType.String:\n                return new ${name}.${stringCase}(reader.GetString()!);`);
    writes.push(`            case ${name}.${stringCase} typed:\n                writer.WriteStringValue(typed.Value);\n                return;`);
  }
  if (boolCase) {
    cases.push(`    public sealed class ${boolCase}(bool value) : ${name}\n    {\n        public bool Value { get; } = value;\n    }`);
    reads.push(`            case JsonTokenType.True:\n            case JsonTokenType.False:\n                return new ${name}.${boolCase}(reader.GetBoolean());`);
    writes.push(`            case ${name}.${boolCase} typed:\n                writer.WriteBooleanValue(typed.Value);\n                return;`);
  }
  if (numberCase) {
    cases.push(`    public sealed class ${numberCase}(double value) : ${name}\n    {\n        public double Value { get; } = value;\n    }`);
    reads.push(`            case JsonTokenType.Number:\n                return new ${name}.${numberCase}(reader.GetDouble());`);
    writes.push(`            case ${name}.${numberCase} typed:\n                writer.WriteNumberValue(typed.Value);\n                return;`);
  }
  if (arrayCase) {
    cases.push(`    public sealed class ${arrayCase}(IReadOnlyList<${elementType}> value) : ${name}\n    {\n        public IReadOnlyList<${elementType}> Value { get; } = value;\n    }`);
    reads.push(`            case JsonTokenType.StartArray:\n            {\n                var items = new List<${elementType}>();\n                while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)\n                {\n                    items.Add(Read(ref reader, typeToConvert, options)${shape.hasNull ? "" : ` ?? throw new JsonException("${name} array items cannot be null.")`});\n                }\n                return new ${name}.${arrayCase}(items);\n            }`);
    writes.push(`            case ${name}.${arrayCase} typed:\n                writer.WriteStartArray();\n                foreach (var item in typed.Value)\n                {\n                    if (item is null) writer.WriteNullValue();\n                    else Write(writer, item, options);\n                }\n                writer.WriteEndArray();\n                return;`);
  }
  cases.push(`    public sealed class ${objectCase}(${objectType} value) : ${name}\n    {\n        public ${objectType} Value { get; } = value;\n    }`);
  // GetTypeInfo keeps the converter trim/AOT-warning-free; the consumer registers the member
  // type in its JsonSerializerContext, as it already does for every contract type it reads.
  reads.push(`            case JsonTokenType.StartObject:\n            {\n                var value = (${objectType}?)JsonSerializer.Deserialize(ref reader, options.GetTypeInfo(typeof(${objectType})));\n                return value is null ? null : new ${name}.${objectCase}(value);\n            }`);
  writes.push(`            case ${name}.${objectCase} typed:\n                JsonSerializer.Serialize(writer, typed.Value, options.GetTypeInfo(typeof(${objectType})));\n                return;`);

  return `[JsonConverter(typeof(${converter}))]\npublic abstract class ${name}\n{\n    private protected ${name}()\n    {\n    }\n\n${cases.join("\n\n")}\n}\n\npublic sealed class ${converter} : JsonConverter<${name}>\n{\n    public override ${name}? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)\n    {\n        switch (reader.TokenType)\n        {\n            case JsonTokenType.Null:\n                return null;\n${reads.join("\n")}\n            default:\n                throw new JsonException($"${name} cannot start with token '{reader.TokenType}'.");\n        }\n    }\n\n    public override void Write(Utf8JsonWriter writer, ${name} value, JsonSerializerOptions options)\n    {\n        switch (value)\n        {\n${writes.join("\n")}\n            default:\n                throw new JsonException($"Unknown ${name} case '{value.GetType().FullName}'.");\n        }\n    }\n}\n`;
}

function isHttpMetadata(program: Program, property: ModelProperty): boolean {
  return isHeader(program, property) || isStatusCode(program, property);
}

function inheritedProperties(model: Model): ModelProperty[] {
  const byName = new Map<string, ModelProperty>();
  const lineage: Model[] = [];
  for (let current: Model | undefined = model; current; current = current.baseModel) {
    lineage.unshift(current);
  }
  for (const current of lineage) {
    for (const property of current.properties.values()) byName.set(property.name, property);
  }
  return [...byName.values()];
}

function renderEnum(_program: Program, enm: Enum): string {
  const enumMembers = [...enm.members.values()];
  const usesStringValues = enumMembers.some((m) => typeof m.value !== "number");
  const converter = usesStringValues
    ? `[JsonConverter(typeof(JsonStringEnumConverter<${enm.name}>))]\n`
    : "";
  const members = enumMembers.map((m) => {
    const wireValue = typeof m.value === "string" ? m.value : m.name;
    const nameAttribute = usesStringValues
      ? `    [JsonStringEnumMemberName("${escapeCsharpString(wireValue)}")]\n`
      : "";
    const valueSuffix = typeof m.value === "number" ? ` = ${m.value}` : "";
    return `${nameAttribute}    ${pascal(m.name)}${valueSuffix}`;
  }).join(",\n");
  return `${converter}public enum ${enm.name}\n{\n${members}\n}\n`;
}

function pascal(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

function escapeCsharpString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
